name: Build and Deploy

on:
  push:
    branches:
      - main  # 或 master，根据你的默认分支名称而定

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate heatmap HTML
        run: python generate.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # 假设你生成的 HTML 存放在 output 文件夹
          publish_branch: gh-pages
          force_orphan: true
