name: Update Heatmap

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate heatmap data
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          echo "替换 notion.py 中的密钥变量为环境变量"
          sed -i 's|NOTION_API_KEY = .*|NOTION_API_KEY = "'"$NOTION_API_KEY"'"|' notion.py
          sed -i 's|DATABASE_ID = .*|DATABASE_ID = "'"$DATABASE_ID"'"|' notion.py
          python generate_heatmap.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update heatmap data"
          git push
